/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ErrorCard: typeof import('./src/components/errors/ErrorCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginCard: typeof import('./src/components/auth/LoginCard.vue')['default']
    MainCard: typeof import('./src/components/main/MainCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
